// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/dataFile.proto

/*
Package converter is a generated protocol buffer package.

It is generated from these files:
	protobuf/dataFile.proto

It has these top-level messages:
	PbDataRow
	PbDataFile
*/
package converter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PbDataRow struct {
	Key  int32     `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Data []float32 `protobuf:"fixed32,2,rep,packed,name=data" json:"data,omitempty"`
}

func (m *PbDataRow) Reset()                    { *m = PbDataRow{} }
func (m *PbDataRow) String() string            { return proto.CompactTextString(m) }
func (*PbDataRow) ProtoMessage()               {}
func (*PbDataRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PbDataRow) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *PbDataRow) GetData() []float32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type PbDataFile struct {
	Rows []*PbDataRow `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
}

func (m *PbDataFile) Reset()                    { *m = PbDataFile{} }
func (m *PbDataFile) String() string            { return proto.CompactTextString(m) }
func (*PbDataFile) ProtoMessage()               {}
func (*PbDataFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PbDataFile) GetRows() []*PbDataRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*PbDataRow)(nil), "converter.PbDataRow")
	proto.RegisterType((*PbDataFile)(nil), "converter.PbDataFile")
}

func init() { proto.RegisterFile("protobuf/dataFile.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0x49, 0x2c, 0x49, 0x74, 0xcb, 0xcc, 0x49, 0xd5, 0x03, 0x8b,
	0x08, 0x71, 0x26, 0xe7, 0xe7, 0x95, 0xa5, 0x16, 0x95, 0xa4, 0x16, 0x29, 0x19, 0x72, 0x71, 0x06,
	0x24, 0xb9, 0x24, 0x96, 0x24, 0x06, 0xe5, 0x97, 0x0b, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a,
	0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0x98, 0x42, 0x42, 0x5c, 0x2c, 0x20, 0xbd, 0x12, 0x4c,
	0x0a, 0xcc, 0x1a, 0x4c, 0x41, 0x60, 0xb6, 0x92, 0x19, 0x17, 0x17, 0x44, 0x0b, 0xc8, 0x44, 0x21,
	0x0d, 0x2e, 0x96, 0xa2, 0xfc, 0xf2, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x11, 0x3d,
	0xb8, 0xd1, 0x7a, 0x70, 0x73, 0x83, 0xc0, 0x2a, 0x92, 0xd8, 0xc0, 0x96, 0x1b, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xc2, 0x6e, 0x51, 0x7d, 0x97, 0x00, 0x00, 0x00,
}
